BULK INSERT VBSPASDatamartTST.dbo.INSDOC_ARCHIVE
FROM 'D:\EXT-INSPRO-INSDOC-ARCHIVE.dat'
WITH
(KEEPIDENTITY,FIELDTERMINATOR = '|',ROWTERMINATOR = '|\n', KEEPNULLS,TABLOCK)
GO


--SELECT count (*) FROM VBSPASDatamartTST.dbo.INSDOC_ARCHIVE

--truncate table VBSPASDatamartTST.dbo.INSDOC_ARCHIVE