USE [VBSPASDatamartRPT]
GO
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ACCOUNT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ACCOUNT_ROLE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ADDRESS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Address_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ADL_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AdminFeeSchedDetails',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_ADJUSTMENT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_APPOINTMENT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_BALANCE_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_HIERARCHY_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_LICENSE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AGENT_TRACKING',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'AltBenefitQuotes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Audit_Queue_Action_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BENEFICIARY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Benefit',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Benefit_Service_Maximums',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Benefit_Services',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Benefit_Type_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BENEFIT_UNDERWRITING_BASE_RECORD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BENEFIT_UNDERWRITING_DETAIL_RECORD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BillCredSchedDetails',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BillFeeSchedDetails',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BILLING_FEES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BILLING_FILE_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'BILLING_FILE_XREF',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CauseOf_Death_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CHECK_DETAIL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CHECK_HEADER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLAIM',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Adjustment_Reason_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Assesment_ADL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_AssesmentClaimantInfo',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Assessment',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Assessment_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Assessment_NurseInfo',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Audit_Amts',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Audit_Queue',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Automated_Followup',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLAIM_BENEFIT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Checklist_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Claimant_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Configurations',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Contact',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Contestability',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Coverage_Election',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Coverage_Plan',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Eligibility',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Eligibility_CheckList',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Eligibility_ICDCodes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Form',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Inspro_Claimant_Details',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Letters',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Manager_Review',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Medical_Review',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_MedsRules_Queue',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Memo_Details',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Accumulator_Adjustment',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Calculation',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Details',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Maximum_Amounts',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Preferences',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Rollup',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Service_Coverage_Audit',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Service_Payee',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Status_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_TransId_Generation',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Product_Code_Groupings',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Register',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Register_Processor',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Status_Category_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Status_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Status_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Types_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claimant_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLI_EMP_CLASS_BEN_OPTS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLI_EMP_CLASS_BEN_PKGS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLI_EMP_CLASS_CORE_BEN_OPTS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLI_EMP_CLASS_CORE_BENS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLI_EMPLOYEE_CLASS_PORT_RULES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_ASSOCIATION_RECORD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_EMPLOYEE_CLASS_GENERAL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_EMPLOYEE_CLASS_RULES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_GROUP_POLICY_DATA',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_INFORMATION',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_INFORMATION_FEE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_LIST_BILL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLIENT_RATE_FACTORS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ClientFeeScheds',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ClientQLEConfig',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CLM_Address',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COMM_ACCTG_HIERARCHY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COMMISSION_ACCOUNTING',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COMMISSION_SCHEDULES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Configure835ContactInformation',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CONTACT_ROLE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ContactInfo',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CONTRACT_POLICY_BALANCE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COVERAGE_ADJUSTMENTS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COVERAGE_RATING_AGE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COVERAGE_SOLICITAT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COVERAGECHANGERECORD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'COVERED_CHILD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CPT_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CPT_Modifier_Categories',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CPT_Modifiers',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'CRH',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Deductible_Adjustments',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Deductible_Rule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'DIARY_RECORDS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'DiscountRules',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'DiscountRulesets',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'elig_Address',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'elig_FinderEligibility',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'elig_Person',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'elig_PersonAddress',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'elig_Products',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ELIG_UW_RULE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ELIG_UW_RULE_BY_REL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ELIG_UW_RULE_STATUS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'EMPLOYEE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'EMPLOYMENT_STATUS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Entity_Contact_Reference',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Esc_Group_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Exclusive_Benefit_Services',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Exclusive_Plan_Benefits',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Exempt_Cov_Status',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Facility_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'FeeSchedules',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'FinderElig',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'FKs',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Frequency_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Graded_Benefit_Schedule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupProductBillingRateKeyDef',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupProductBillingRateKeyTypeData',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupProductBillingRateKeyValue',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupProductBillingRateTable',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupProductBillingRateTableRow',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'GroupReasonCodeMapping',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HCPCS_Ambulance_Modifiers',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HCPCS_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HCPCS_Copay_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HCPCS_Exceptions',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HCPCS_Level_II_Modifiers',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'HL_AGENT_HIERARCHY_LIST',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ICD_Exceptions',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ICD10_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ICD9_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'INDIVIDUAL_BILLING',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'INFLATED_BENEFIT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'INSDOC_ARCHIVE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'INSPRO_TABLES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'INSURANCE_PAYMENT_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Interest_Calculation_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ISS_ST_ASGMNT_RULEID_DT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ISS_ST_ASGMNT_RULEID_HD',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LB_Adjustments',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LimitingChargesHCPCSExceptions',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LimitingChargesStateExclusion',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LOAN',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LOAN_HISTORY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LOAN_RULE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LOAN_RULE_INTEREST',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'LOAN_RULE_MAXIMUM',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MasterProvider',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MasterProvider_Contacts',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MasterProvider_Status_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Maximum_Type_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Memo',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MIBRxRule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MIBRxRuleset',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'MIBRxTransmssnHeader',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'NCP',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'NDL_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Network',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Network_Benefit_Discounts',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'NFA',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Payment_Schedule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PersonQLEs',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Place_Of_Service',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Place_Of_Service_Type_List',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_ADL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_ADL_Info',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Benefit_Maximums',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Benefits',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_CARules',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_CheckList',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Claimant',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PLAN_PAY_UP',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Preface_Coverage',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Preface_Maximums',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PLAN_STRUCTURE_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PLAN_STRUCTURE_STATES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PLAN_STRUCTURE_SUPP_BENEFITS',@role_name = NULL	
--EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLBEN',@role_name = NULL -- Commented as it was dropped in Inspro Rel2.2c code drop
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLICY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Policy_Claim_Data',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLICY_DIRECT_BILL_HISTORY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Policy_NFO_Overrides',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLICY_OFFER_INCREASE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Policy_Preauthorization',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLICY_REQUIREMENTS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PolicyDiscount',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PortRuleDtl',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PortRuleHdr',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PREM_RATE_DET',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Preventive_Care_Exceptions',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Processor_Calendar',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ProdOffFeeScheds',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_AGENT_SPLITS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_AUTHORIZATION',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_AUTHORIZATION_BROKERS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_BENEFIT_DATA',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_BENEFIT_DATA_NON_EE_OVERRIDE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_BENEFIT_LTC_SPECIFIC',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_BENEFITS_NON_LTC',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_COMPANIES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_EMPLOYER_PAID_BENEFITS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_FULLFILLMENT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_INCREASE_OFFER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_INCREASE_OFFER_HISTORY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_LIST_BILL',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_MEDIA_CIRC_ACTUALS',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_STATES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING_WORKSITE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Provider',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Provider_Network_Associations',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Provider_Status_History',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ProviderAddress',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ProviderLicense',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Recoup_Payment',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Remark_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ReratePolicyDetails',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Revenue_Code_Exceptions',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Revenue_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'RT_COMMISSION_SCHEDULES',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'RTG_DB_EXTRACT_INFO',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'RxResponseHeader',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SALARY_HISTORY',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'ServiceCoverageStateWithhold',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SOLICITATION',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SPLIT_COMMISSION',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SPLIT_COMMISSION_AGENT',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'State_Interest_Rules',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'StateWithholding',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SUB_BENEFIT_MASTER',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SUB_BENEFIT_PLAN',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'SUSPENSE',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'TmkCodes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'TPA',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'User_Processing_Rule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'User_Processing_Rule_Param',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Value_Codes',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Vendor',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'VendorAddress',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'VendorFeeType',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'VendorLicense',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'W9BackUpWithhold',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Waiting_Period_Rule',@role_name = NULL	
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Activity_History',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'PRODUCT_OFFERING',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Search_Sort_Fields',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Audit_Reason_Codes',@role_name = NULL
--EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Payment_Status_Codes',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Claim_Search_Filter_Fields',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'Plan_Preface_User_Processing_Rule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = N'dbo',@source_name = N'POLICY_COMMIS_ADVANCE_DTL',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'POLICY_COMMISSION_ADVANCE',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Provider_Network_Benefit_Discounts',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'UNDERWRITING_FORM_DEFINITION',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'UNDERWRITING_FORM_QUESTIONS',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Policy_Preauthorization_Procedure_Codes',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'AGENT_CONTRACT',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Claim_Audit_Counts',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Claim_Audit_Rules',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Claim_Payment_Check_EFT_Details',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Claim_Payment_Service_Coverage',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'CLIENT_EMPLOYEE_CLASS',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'COVERAGE',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERAL_LEDGER_DATA',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MEMO_RECORDS',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Next_FollowUp_Activity_list',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PERSON',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Plan_Preface',@role_name = NULL
--EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'POLICY',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Processor_Claim_Limits',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Processor_Details',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'REQUIREMENTS',@role_name = NULL


/* Inspro Code Drop 2.2a New Tables */

EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ActMemberPolicyData',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ActMemberPolicyDataUL',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ActPolicyLoanData',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ActPolicyLoanDataUL',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MIBReplyPartyDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MIBReplyPartyPriorNames',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MIBResponseHeader',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MIBTransResultErrorDesc',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PasTransactionReportUL',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Policy_Activity_History',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Premium_Rate_Header',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Premium_Rate_Index',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Premium_Rate_Master',@role_name = NULL

/* Inspro Code Drop 2.2b New Tables */

EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'AdminFeeRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'AdminFeeRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'AnnuityPeriodsFunds',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'AnnuityPeriodsTransactionRules',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BEN_PROC_DETAIL',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BEN_PROC_MASTER',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BenefitRiderRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BenefitRiderRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BonusInterestInfo',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BPR_REQD_PROHIBIT',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'DeathBenefitOptionRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'DeathBenefitOptionRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'DISASTER_AREA_INFO',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FaceChangeRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FaceChangeRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FixedFundDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FreeLook_Rule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FreeLook_Rule_States',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Fund',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'FundDetail',@role_name = NULL
/*
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_205CTRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_205IntBon_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_205LWSTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_205SrPct_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_594CTRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_594GCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_594LWSTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_899CTRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_899LWSTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ABCOIALX_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ABCOIALXP1_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ABCOIALXP2_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXADBTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXCTRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXLWSTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1CCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1CInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1GCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1HHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1LnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1SrPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1TP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP1XOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2CCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2CInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2GCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2HHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2LnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2SrPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2TP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXP2XOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXWPTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ALXXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_CSO1980_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_CSO2001_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_CSO2001250_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1CF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1CIn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1LCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1PFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC1SPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2CF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2CIn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2LCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2PFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULC2SPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GIULTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GLOBADBTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GLOBBXRLTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GLOBULCITP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_GLOBWPTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_HundredPct_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1CF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1CIn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1LnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1PFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC1SPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2CF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2CIn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2Gint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2LnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2PFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULC2SPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULCXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_PPULXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULBRRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULBXRCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULBXRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULCOR_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULCurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULGurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULHHCTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULNYSRP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULTPI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TGULXOBTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_ThirteenAn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCCF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCCIn_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCSPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULCXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TPULXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULBRRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULBXRCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULBXRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCBRRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCBXRCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCF_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCOR_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCCurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCGurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCNYSRP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCOR_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULCXOBTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEBRRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEBXRCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEBXRTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULECCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULECInt_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULECOR_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULECurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEGurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEHHCTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULELnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULENYSRP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULESurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULETP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULETPI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULEXOBTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULGCOI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULGint_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULGurPC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULHHCC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULHHCTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULLnCr_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULNYSRP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULPFS_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULSurPrm_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULTP_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULTPI_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULXOBC_ZZZZ',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'GENERATED_Rate_TULXOBTP_ZZZZ',@role_name = NULL
*/
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ISLoanRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ISLoanRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'LoanFundDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MaturityRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MaturityRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MonthaversaryRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'MonthaversaryRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PaymentRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PaymentRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PLAN_BENEFIT_MEMO',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PlanCodeFile',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'POL_REINSTATE_HISTORY',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PremiumChargeRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PremiumChargeRuleDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'PremiumRateFactors',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Rule7702',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Rule7702Detail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ShadowFundDetail',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'StateWithholdRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'StateWithholdRuleStates',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Transaction_Detail_Doc',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'Transaction_Rules',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ULRules',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'UNDERWRITING_QUES_TEXT',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'USER_PROFILE',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'USER_ROLES',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'WithdrawalRule',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'WithdrawalRuleDetail',@role_name = NULL

/* Inspro Code Drop 2.2c New Tables */

EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ExternalDocument',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'ExternalDocumentRequirements',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'POLBEN_MASTER',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'POLBEN_RTG_ATTRIBUTES',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'SecQualifiers',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'SecUserQualifiers',@role_name = NULL
EXEC sys.sp_cdc_enable_table @source_schema = 'dbo',@source_name = 'BENEFITCHANGEACTIONPERLEVEL',@role_name = NULL

/* Script to add 30-days rolling clean up */

UPDATE  [msdb].[dbo].[cdc_jobs]
SET [retention] = 43200,
[threshold] = 50000
WHERE [database_id] = DB_ID('VBSPASDatamartRPT')
AND [job_type] = 'cleanup'

print 'CDC enabled successfully on VBSPasDatamartRpt tables!!!!';
Go






	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
