SELECT p.name, o.name, d.*
FROM sys.database_principals AS p
JOIN sys.database_permissions AS d ON d.grantee_principal_id = p.principal_id
JOIN sys.objects AS o ON o.object_id = d.major_id



SELECT 'GRANT CONNECT TO ['+ name + ']'  FROM sys.sysusers 
WHERE hasdbaccess = 1

REVOKE CONNECT FROM [dbo]
GO
REVOKE CONNECT FROM [WorkQueueUser]
GO
REVOKE CONNECT FROM [TMKMHC\C4B]
GO
REVOKE CONNECT FROM [TMKMHC\G1S]
GO
REVOKE CONNECT FROM [TMKMHC\DSR]
GO
REVOKE CONNECT FROM [TMKMHC\G13]
GO
REVOKE CONNECT FROM [FMH\sqlsvr]
GO
REVOKE CONNECT FROM [PSQL03C]
GO
REVOKE CONNECT FROM [TMKMHC\L0G]
GO
REVOKE CONNECT FROM [TMKMHC\M9P]
GO
REVOKE CONNECT FROM [FMH\cbrownfield]
GO
REVOKE CONNECT FROM [TMKMHC\H1H]
GO
REVOKE CONNECT FROM [TMKMHC\F0S]
GO
REVOKE CONNECT FROM [tmkmhc\altovasvc]
GO
REVOKE CONNECT FROM [DSQL03]
GO
REVOKE CONNECT FROM [PSQL03A]
GO
REVOKE CONNECT FROM [TMKMHC\B1L]
GO
REVOKE CONNECT FROM [TMKMHC\D10]
GO
REVOKE CONNECT FROM [TMKMHC\B12]
GO
REVOKE CONNECT FROM [TMKMHC\A1O]
GO
REVOKE CONNECT FROM [TMKMHC\B02]
GO
REVOKE CONNECT FROM [LinkFrmRPT01B]
GO
REVOKE CONNECT FROM [TMKMHC\LLL]
GO
REVOKE CONNECT FROM [TMKMHC\T1C]
GO
REVOKE CONNECT FROM [TMKMHC\S15]
GO
REVOKE CONNECT FROM [TMKMHC\K31]
GO
REVOKE CONNECT FROM [ds_user]
GO
REVOKE CONNECT FROM [DS_USERP_RO]
GO
REVOKE CONNECT FROM [TMKMHC\R0V]
GO
REVOKE CONNECT FROM [TMKMHC\K0A]
GO
REVOKE CONNECT FROM [mk6]
GO
REVOKE CONNECT FROM [FamilyFilesUser]
GO
REVOKE CONNECT FROM [TMKMHC\N43]
GO
REVOKE CONNECT FROM [LinkFrmPSQL03B]
GO
REVOKE CONNECT FROM [TMKMHC\S24]
GO
REVOKE CONNECT FROM [TMKMHC\E3F]
GO
REVOKE CONNECT FROM [WQ_EOBUser]
GO
REVOKE CONNECT FROM [TMKMHC\J2S]
GO
REVOKE CONNECT FROM [TMKMHC\R0W]
GO