USE [VBSPASDatamart]

GO
--ALTER INDEX [dbo_COMMISSION_ACCOUNTING_CT_idx] ON [cdc].[dbo_COMMISSION_ACCOUNTING_CT] REBUILD
--PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
--ALLOW_PAGE_LOCKS = ON)
--GO

GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ActMemberPolicyDataUL] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_COVERAGE] ON [dbo].[COVERAGE] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO



GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATA] ON [dbo].[ActMemberPolicyData] 
REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO
GO
--ALTER INDEX [dbo_COVERAGE_CT_idx] ON [cdc].[dbo_COVERAGE_CT] REBUILD
--PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
--ALLOW_PAGE_LOCKS = ON)
--GO
GO
--ALTER INDEX [dbo_GENERAL_LEDGER_DATA_CT_idx] ON [cdc].[dbo_GENERAL_LEDGER_DATA_CT] REBUILD
--PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
--ALLOW_PAGE_LOCKS = ON)
--GO
GO
--ALTER INDEX [dbo_POLBEN_RTG_ATTRIBUTES_CT_idx] ON [cdc].[dbo_POLBEN_RTG_ATTRIBUTES_CT] REBUILD
--PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
--ALLOW_PAGE_LOCKS = ON)
--GO
GO
--ALTER INDEX [dbo_INSURANCE_PAYMENT_MASTER_CT_idx] ON [cdc].[dbo_INSURANCE_PAYMENT_MASTER_CT] REBUILD
--PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
--ALLOW_PAGE_LOCKS = ON)
--GO

GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ActMemberPolicyDataUL] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

USE [VBSDMOds];
GO
ALTER INDEX [PK_FirstActionDate_FirstActionReason_AccountNumber_AccountType_AcctDiaryNo_CompanyCode_PolicyNumber_RowNoId] ON [dbo].[PAS_DIARY_RECORDS] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_AccountType_AccountNumber_CompanyCode_PolicyNumber_BenefitAttr_EffectiveDate_RowNoId] ON [dbo].[PAS_POLBEN_RTG_ATTRIBUTES] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [CX_POLICY_NO] ON [dbo].[STG_PIOP_FM_KEEP] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [CX_POLICY_NO] ON [dbo].[STG_PIOP_FM_KEEP] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_CompanyCode_PersonNumber_PolicyNumber_RecordNumber_RowNoId] ON [dbo].[PAS_COVERAGE] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO


USE [VBSDMReference];
GO
ALTER INDEX [IX_BadInd_RowCurrentInd_IdTypeNm] ON [dbo].[STG_CopyClientXref] REBUILD
PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [CX_ClientIntegrationId] ON [dbo].[STG_CopyClientXref] REBUILD;
GO
