USE [VBSPASDatamartRPT]
GO
ALTER INDEX [dbo_AGENT_LICENSE_CT_idx] ON [cdc].[dbo_AGENT_LICENSE_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [dbo_AGENT_APPOINTMENT_CT_idx] ON [cdc].[dbo_AGENT_APPOINTMENT_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_ActMemberPolicyData_CT_idx] ON [cdc].[dbo_ActMemberPolicyData_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_PERSON_CT_idx] ON [cdc].[dbo_PERSON_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_INSPRO_TABLES_CT_idx] ON [cdc].[dbo_INSPRO_TABLES_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_UNDERWRITING_FORM_QUESTIONS_CT_idx] ON [cdc].[dbo_UNDERWRITING_FORM_QUESTIONS_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_DIARY_RECORDS_CT_idx] ON [cdc].[dbo_DIARY_RECORDS_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_MEMO_RECORDS_CT_idx] ON [cdc].[dbo_MEMO_RECORDS_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_ActMemberPolicyDataUL_CT_idx] ON [cdc].[dbo_ActMemberPolicyDataUL_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_INSURANCE_PAYMENT_MASTER_CT_idx] ON [cdc].[dbo_INSURANCE_PAYMENT_MASTER_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_POLBEN_RTG_ATTRIBUTES_CT_idx] ON [cdc].[dbo_POLBEN_RTG_ATTRIBUTES_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_COMM_ACCTG_HIERARCHY_CT_idx] ON [cdc].[dbo_COMM_ACCTG_HIERARCHY_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_GENERAL_LEDGER_DATA_CT_idx] ON [cdc].[dbo_GENERAL_LEDGER_DATA_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_COMMISSION_ACCOUNTING_CT_idx] ON [cdc].[dbo_COMMISSION_ACCOUNTING_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_CRH_CT_idx] ON [cdc].[dbo_CRH_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [dbo_POLICY_REQUIREMENTS_CT_idx] ON [cdc].[dbo_POLICY_REQUIREMENTS_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [dbo_COVERAGE_CT_idx] ON [cdc].[dbo_COVERAGE_CT] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATA] ON [dbo].[ActMemberPolicyData] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ACTMEMBERPOLICYDATAUL] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ACTMEMBERPOLICYDATAUL] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATA] ON [dbo].[ACTMEMBERPOLICYDATA] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ACTMEMBERPOLICYDATAUL] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

GO
ALTER INDEX [PK_COVERAGE] ON [dbo].[COVERAGE] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

USE [VBSPASDatamartCNV];
GO
ALTER INDEX [PK_MEMO_RECORDS] ON [dbo].[MEMO_RECORDS] REBUILD;
GO
