USE [VBSPASDatamart]
GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATAUL] ON [dbo].[ACTMEMBERPOLICYDATAUL] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
GO
ALTER INDEX [PK_ACTMEMBERPOLICYDATA] ON [dbo].[ACTMEMBERPOLICYDATA] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


GO
ALTER INDEX [PK_COVERAGE] ON [dbo].[COVERAGE] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO


USE [VBSAnalytics]
GO
ALTER INDEX [PK_FactPDClientRank] ON [dbo].[FactPDClientPymtScore] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

USE [VBSDMReference];
GO
ALTER INDEX [IX_BadInd_RowCurrentInd_IdTypeNm] ON [dbo].[STG_CopyClientXref] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO
USE [VBSDMOds];
GO
ALTER INDEX [CX_POLICY_NO] ON [dbo].[STG_PIOP_FM_KEEP] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

USE [VBSDMReference];
GO
ALTER INDEX [CX_ClientIntegrationId] ON [dbo].[STG_CopyClientXref] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO
